from pydantic import BaseModel, Field
from agents import Agent

INSTRUCTIONS = (
    "You are a strict senior judge tasked with evaluating ideas for a given query. "
    "You will be provided with the original query and some initial ideas generated by a research assistant.\n"
    "For each idea, score it on the following dimensions (0–10 each): Relevance, Novelty, Feasibility, and Value. "
    "For each idea, indicate which dimension is the main reason for a low score if applicable (failure reason signal).\n"
    "Think carefully and do not agree with the ideas just because they are presented to you."
)


class Scores(BaseModel):
    relevance: float = Field(ge=0, le=10)
    novelty: float = Field(ge=0, le=10)
    feasibility: float = Field(ge=0, le=10)
    value: float = Field(ge=0, le=10)
    
class IdeaEvaluation(BaseModel):
    title: str = Field(description="The title of the idea")
    description: str = Field(description="Detailed description of the idea")
    why_it_matters: str = Field(description="Explanation of the idea's importance and impact")
    scores: Scores = Field(description="Evaluation scores across different dimensions")
    final_score: float = Field(description="Overall evaluation score", ge=0, le=10)
    failure_reason: str | None = Field(description="Main dimension causing a low score, if applicable")
    sources: list[str] = Field(description="List of references or sources supporting the idea")

class EvaluationResult(BaseModel):
    ideas: list[IdeaEvaluation] = Field(description="A list of evaluated ideas with scores and reasons.")


evaluator_agent = Agent(
    name="EvaluatorAgent",
    instructions=INSTRUCTIONS,
    model="o3-mini-2025-01-31",
    output_type=EvaluationResult,
)